# revision_marker: pr_4
"""auto_pr_4

Revision ID: 1d01d3c522c9
Revises: 87caf98e61bf
Create Date: 2026-03-24 00:47:50.827193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d01d3c522c9'
down_revision: Union[str, Sequence[str], None] = '87caf98e61bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('test_field32', sa.String(length=255), nullable=False))
    op.drop_column('users', 'test_field33')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('test_field33', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('users', 'test_field32')
    # ### end Alembic commands ###
