# revision_marker: pr_1
"""auto_pr_1

Revision ID: 721c44e2927a
Revises: 1cd3b04277c8
Create Date: 2026-03-24 00:06:51.399806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '721c44e2927a'
down_revision: Union[str, Sequence[str], None] = '1cd3b04277c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('test_field2', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('test_field3', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'test_field3')
    op.drop_column('users', 'test_field2')
    # ### end Alembic commands ###
