# revision_marker: pr_2
"""auto_pr_2

Revision ID: 385a0236db3d
Revises: aba7ba8e5477
Create Date: 2026-03-24 00:31:36.833430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '385a0236db3d'
down_revision: Union[str, Sequence[str], None] = 'aba7ba8e5477'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('test_field33', sa.String(length=255), nullable=False))
    op.drop_column('users', 'test_field3')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('test_field3', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('users', 'test_field33')
    # ### end Alembic commands ###
