# revision_marker: pr_1
"""auto_pr_1

Revision ID: 3e0f6fafaf31
Revises: 1cd3b04277c8
Create Date: 2026-03-24 00:04:46.505314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e0f6fafaf31'
down_revision: Union[str, Sequence[str], None] = '1cd3b04277c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('test_field', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'test_field')
    # ### end Alembic commands ###
