name: PR

on:
  pull_request:
    branches: [main]

jobs:
  migrate:
    uses: ./.github/workflows/migrate.yml
    with:
      pr_number: ${{ github.event.pull_request.number }}
      head_ref: ${{ github.head_ref }}
    permissions:
      contents: write

  test:
    needs: migrate
    uses: ./.github/workflows/test.yml
    with:
      head_ref: ${{ github.head_ref }}